import type { BlogPostRecord, ProjectRecord, SkillRecord } from "@/lib/cms-types";

const now = "2026-05-18T00:00:00.000Z";

export const defaultProjects: ProjectRecord[] = [
  {
    id: "project-douban-top250",
    slug: "douban-top250-crawler",
    name: "豆瓣 Top250 爬虫",
    type: "学习项目",
    time: "课程练习",
    summary: "围绕豆瓣 Top250 电影数据完成采集、解析、清洗和结构化整理，练习从网页信息到可分析数据的完整流程。",
    bodyMarkdown:
      "## 项目目标\n\n用 Python 完成一个电影数据采集与整理流程，把页面信息转成可保存、可复查、可分析的数据。\n\n## 实现内容\n\n- 使用请求库获取页面内容\n- 解析电影名称、评分、简介等字段\n- 清洗文本并保存为结构化数据\n- 记录访问频率、页面结构变化和异常处理\n\n## 收获\n\n这个项目让我把课堂里的 Python 基础和真实网页数据联系起来，也让我更重视访问规则、错误处理和数据清洗质量。",
    takeaway: "理解了爬虫请求、解析、存储的基本链路，也认识到数据采集必须尊重网站规则和访问频率限制。",
    stack: ["Python", "Web Scraping", "Data Processing"],
    tags: ["Python", "爬虫", "数据处理"],
    status: "published",
    sortOrder: 10,
    updatedAt: now,
  },
  {
    id: "project-coyin",
    slug: "coyin-reader-app",
    name: "Coyin 知页软件开发",
    type: "学习项目",
    time: "个人实践",
    summary: "面向学习和论文阅读的桌面软件设想，聚合资料检索、PDF 阅读和计划管理，让学习材料更容易被持续整理。",
    bodyMarkdown:
      "## 项目目标\n\n把论文阅读、资料检索和学习计划整理到同一个桌面工具中，减少资料分散带来的上下文切换。\n\n## 功能方向\n\n- PDF 阅读与资料整理\n- 学习计划和任务拆分\n- 面向个人学习流程的界面设计\n- 对常用资料建立可追踪的索引\n\n## 收获\n\n这个项目让我开始从“功能能不能做”转向“一个工具是否真的符合日常学习习惯”。",
    takeaway: "练习把多个学习场景整合进同一个软件界面，关注信息检索、阅读体验和任务管理之间的协同。",
    stack: ["Desktop App", "PDF Reader", "Planning"],
    tags: ["桌面应用", "PDF", "学习工具"],
    status: "published",
    sortOrder: 20,
    updatedAt: now,
  },
  {
    id: "project-ecg",
    slug: "ecg-diagnosis-system",
    name: "ECG 信号智能诊断系统",
    type: "学习项目",
    time: "AI 实验",
    summary: "基于 ECG 相关数据和模型训练流程进行智能诊断实验，探索深度学习在医学信号分析中的应用。",
    bodyMarkdown:
      "## 项目目标\n\n围绕 ECG 信号数据构建一个智能诊断实验流程，理解医学信号项目从数据到模型评估的关键步骤。\n\n## 技术重点\n\n- 医学信号数据预处理\n- PyTorch 模型训练与评估\n- 指标记录、误差分析和结果表达\n- 对医学 AI 项目保持谨慎、可复查的表达方式\n\n## 收获\n\n这个项目让我意识到，模型效果只是其中一部分；数据来源、标注质量、实验复现和结论边界同样重要。",
    takeaway: "重点练习数据预处理、模型训练、推理评估和医学 AI 项目表达的严谨性。",
    stack: ["Python", "PyTorch", "Deep Learning"],
    tags: ["PyTorch", "深度学习", "医学 AI"],
    status: "published",
    sortOrder: 30,
    updatedAt: now,
  },
];

export const defaultSkills: SkillRecord[] = [
  {
    id: "skill-c-cpp",
    slug: "c-cpp",
    name: "Programming",
    title: "C / C++",
    summary: "用底层语言训练算法思维，理解数据结构、内存和程序执行过程。",
    bodyMarkdown:
      "## 学习重点\n\n- 数据结构与算法\n- 指针、内存和程序执行模型\n- C/C++ 基础工程实践\n\n## 目前使用场景\n\n我主要用 C/C++ 训练基础能力，包括刷题、理解底层执行过程，以及为后续系统和高性能方向打基础。",
    tags: ["C", "C++", "Algorithm"],
    levelLabel: "Foundation",
    status: "published",
    sortOrder: 10,
    updatedAt: now,
  },
  {
    id: "skill-python",
    slug: "python",
    name: "Python",
    title: "Python",
    summary: "用于爬虫、数据处理、模型实验和自动化脚本，是当前学习实践中的主力语言。",
    bodyMarkdown:
      "## 使用场景\n\n- 数据采集与处理\n- 机器学习实验脚本\n- 自动化工具\n- 项目原型验证\n\n## 学习方式\n\n我会把 Python 放在具体任务里学习：先完成一个能跑通的流程，再逐步整理异常处理、模块组织和可复现记录。",
    tags: ["Python", "Automation", "Data"],
    levelLabel: "Practical",
    status: "published",
    sortOrder: 20,
    updatedAt: now,
  },
  {
    id: "skill-pytorch",
    slug: "pytorch",
    name: "PyTorch",
    title: "PyTorch",
    summary: "围绕深度学习训练、推理和实验复盘，逐步建立 AI 项目实现能力。",
    bodyMarkdown:
      "## 学习重点\n\n- Tensor 与自动求导\n- Dataset、DataLoader 和训练循环\n- 模型评估与实验记录\n- 结果可视化和复现\n\n## 目前目标\n\n我希望能把模型训练写得更清楚：数据怎么来、模型怎么训、指标怎么解释、失败样本说明了什么。",
    tags: ["PyTorch", "AI", "Training"],
    levelLabel: "Learning",
    status: "published",
    sortOrder: 30,
    updatedAt: now,
  },
  {
    id: "skill-machine-learning",
    slug: "machine-learning",
    name: "Machine Learning",
    title: "ML",
    summary: "关注特征、模型、指标和实验流程，把算法知识落到可验证的结果中。",
    bodyMarkdown:
      "## 学习重点\n\n- 特征工程和数据划分\n- 常见模型与评估指标\n- 实验对比和复盘\n- 过拟合、泛化和误差分析\n\n## 学习态度\n\n机器学习对我来说不是只记模型名称，而是理解每个选择会怎样影响数据、训练和结论。",
    tags: ["Machine Learning", "Metrics", "Experiment"],
    levelLabel: "Core",
    status: "published",
    sortOrder: 40,
    updatedAt: now,
  },
  {
    id: "skill-deep-learning",
    slug: "deep-learning",
    name: "Deep Learning",
    title: "DL",
    summary: "从神经网络、训练技巧到医学信号分析项目，持续扩展模型理解。",
    bodyMarkdown:
      "## 学习重点\n\n- 神经网络基础\n- 训练技巧和调参\n- 医学信号方向实验\n- 论文阅读和模型复现\n\n## 当前方向\n\n我会优先把深度学习和具体项目结合起来，避免只停留在概念层面。",
    tags: ["Deep Learning", "Neural Network", "ECG"],
    levelLabel: "Exploring",
    status: "published",
    sortOrder: 50,
    updatedAt: now,
  },
  {
    id: "skill-cloud-deploy",
    slug: "cloud-deploy",
    name: "Cloud Deploy",
    title: "Cloud",
    summary: "通过 Next.js、SQLite、Nginx 和云服务器理解一个个人网站从开发到上线的完整路径。",
    bodyMarkdown:
      "## 学习重点\n\n- Next.js 应用结构\n- SQLite 内容管理\n- Linux、Nginx 和进程管理\n- 域名、HTTPS 和服务稳定性\n\n## 项目联系\n\n这个网站本身就是我的云端部署练习：前端展示、后台内容管理和服务器运行都会沉淀成可复查的经验。",
    tags: ["Next.js", "SQLite", "ECS", "Nginx"],
    levelLabel: "Deployment",
    status: "published",
    sortOrder: 60,
    updatedAt: now,
  },
];

export const defaultBlogPosts: BlogPostRecord[] = [
  {
    id: "post-learning-map",
    slug: "learning-map",
    title: "我的学习地图",
    date: "2026-05-18",
    summary: "整理目前围绕编程基础、机器学习、深度学习和云部署建立起来的学习路线。",
    bodyMarkdown:
      "## 为什么需要学习地图\n\n我现在学习的内容很多，如果只是零散记录，很容易只记住做过什么，却忘了为什么要做。\n\n这篇文章会作为一个长期入口，用来整理我在编程、AI、项目实践和云部署上的学习脉络。\n\n## 当前主线\n\n- C/C++：训练基础算法和程序执行理解\n- Python：支撑数据处理、爬虫和 AI 实验\n- 机器学习：理解特征、模型、指标和实验设计\n- 深度学习：用 PyTorch 完成可复现的训练与评估\n- 云部署：把个人网站和内容系统真正运行起来\n\n## 记录方式\n\n我希望每篇笔记都尽量回答三个问题：我在解决什么问题、我用了什么方法、这件事让我学到了什么。",
    tags: ["学习记录", "AI", "项目"],
    category: "学习笔记",
    status: "published",
    sortOrder: 10,
    updatedAt: now,
  },
  {
    id: "post-python-crawler-notes",
    slug: "python-crawler-notes",
    title: "Python 爬虫练习记录",
    date: "2026-05-18",
    summary: "从网页请求、HTML 解析到数据清洗，记录一次基础爬虫练习中的关键点。",
    bodyMarkdown:
      "## 练习目标\n\n这次练习的目标不是追求复杂，而是把一个基础数据采集流程写清楚：请求页面、解析字段、清洗文本、保存结果。\n\n## 关键点\n\n- 请求之前先理解页面结构\n- 解析逻辑要能应对字段缺失\n- 保存数据时保留原始来源和处理时间\n- 控制访问频率，避免给目标网站造成压力\n\n## 小结\n\n爬虫项目看起来只是“拿数据”，但真正重要的是让数据来源、处理过程和异常情况都可以被复查。",
    tags: ["Python", "爬虫", "数据处理"],
    category: "项目复盘",
    status: "published",
    sortOrder: 20,
    updatedAt: now,
  },
  {
    id: "post-pytorch-training-loop",
    slug: "pytorch-training-loop",
    title: "PyTorch 训练循环笔记",
    date: "2026-05-18",
    summary: "记录一次从 Dataset、DataLoader 到训练评估循环的 PyTorch 基础整理。",
    bodyMarkdown:
      "## 基础结构\n\n一个清晰的 PyTorch 实验至少需要把数据、模型、损失函数、优化器、训练循环和评估逻辑拆开。\n\n```python\nfor epoch in range(epochs):\n    model.train()\n    for x, y in train_loader:\n        optimizer.zero_grad()\n        pred = model(x)\n        loss = criterion(pred, y)\n        loss.backward()\n        optimizer.step()\n```\n\n## 我需要特别注意的地方\n\n- 训练和评估模式要分开\n- 指标要和任务目标匹配\n- 每次实验保留参数、随机种子和结果\n- 失败样本通常比平均指标更能说明问题",
    tags: ["PyTorch", "深度学习", "实验"],
    category: "AI 笔记",
    status: "published",
    sortOrder: 30,
    updatedAt: now,
  },
  {
    id: "post-cloud-site-notes",
    slug: "cloud-site-notes",
    title: "个人网站的云端运行笔记",
    date: "2026-05-18",
    summary: "记录个人网站从前端页面、内容管理到服务器运行之间的连接关系。",
    bodyMarkdown:
      "## 这个网站在解决什么\n\n我希望它不只是展示页面，而是一个可以长期维护的学习档案：项目、技能、文章和生活记录都能持续更新。\n\n## 当前结构\n\n- 首页：沉浸式时间轴展示主要内容\n- 后台：管理项目、技能和博客文章\n- 数据库：保存可以编辑的正文、标签和发布状态\n- 独立页面：让博客和项目可以被单独阅读、分享和收藏\n\n## 思考\n\n个人网站最重要的不是一次做得很炫，而是内容能够不断积累，并且每次更新都不痛苦。",
    tags: ["Next.js", "SQLite", "云部署"],
    category: "工程记录",
    status: "published",
    sortOrder: 40,
    updatedAt: now,
  },
];
